version: '3.1'

services:
  webserver:
    image: webserver
    build: .
    ports:
      - 80:80
    

  db:
    image: mariadb
    hostname: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MARIADB_USER: web_eng_user
      MARIADB_PASSWORD: linux
      MYSQL_ROOT_PASSWORD: example

volumes:
  db:
