version: '3.1'

services:
  traefik:
    image: traefik:v2.10  # Traefik image version
#    restart: unless-stopped
    command:
      - "--api.insecure=true"                        
      - "--providers.docker=true"                     
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"  # New TLS entrypoint
      - "--providers.file.filename=/dynamic/traefik_dynamic.yml"  # Load dynamic config
    ports:
      - "80:80"                                       
      - "443:443"                                      # Expose port 443 for HTTPS
      - "8080:8080"                                   
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./certs:/certs"  # Mount folder with certs
      - "./traefik_dynamic.yml:/dynamic/traefik_dynamic.yml"  # Mount dynamic config
    depends_on:
      db:
        condition: service_healthy
        restart: true
      webserver:
        condition: service_healthy
        restart: true

  webserver:
    image: webserver
    build: .
#    restart: unless-stopped
#    ports:
#      - 80:80
    volumes:
      - pictures:/var/www/html/pictures
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`localhost`)"
      - "traefik.http.services.webserver.loadbalancer.server.port=80"
      - "traefik.http.routers.webserver.entrypoints=web,websecure"  # Allow both HTTP and HTTPS
      - "traefik.http.routers.webserver.tls=true"  # Enable TLS for this router
    environment:
      DATABASE_USER: web_eng_user
      DATABASE_HOST: mariadb
      DATABASE_PASS: linux
      DATABASE_NAME: web_eng
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  db:
    image: mariadb
    hostname: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MARIADB_USER: web_eng_user
      MARIADB_PASSWORD: linux
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db:
  pictures: