version: '3.1'

services:
  traefik:
    image: traefik:v2.10  # Traefik image version
    restart: unless-stopped
    command:
      - "--api.insecure=true"                        
      - "--providers.docker=true"                     
      - "--entrypoints.web.address=:80"               
    ports:
      - "80:80"                                       
      - "8080:8080"                                   
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"   

  webserver:
    image: webserver
    build: .
    restart: unless-stopped
#    ports:
#      - 80:80
    volumes:
      - pictures:/var/www/html/pictures
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`localhost`)"  
      - "traefik.http.services.webserver.loadbalancer.server.port=80"
    

  db:
    image: mariadb
    hostname: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      MARIADB_USER: web_eng_user
      MARIADB_PASSWORD: linux
      MYSQL_ROOT_PASSWORD: example

volumes:
  db:
  pictures:
