version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_USER: web_eng_user
      MARIADB_PASSWORD: linux
      MYSQL_ROOT_PASSWORD: example

volumes:
  db:
